# Generated by Django 5.2.5 on 2025-08-18 18:41

import django.db.models.deletion
import document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database_manager', '0001_initial'),
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Шрифт',
                'verbose_name_plural': 'Шрифты',
            },
        ),
        migrations.CreateModel(
            name='GroupOfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='VariableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('meaning', models.TextField(blank=True, null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
            },
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manager.profile')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentsPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to=document.models.user_directory_path)),
                ('json', models.JSONField(blank=True, default=dict, null=True, verbose_name='JSON строка')),
                ('documentOfOrganisation', models.BooleanField(blank=True, default=False, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=document.models.user_directory_path)),
                ('lastUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True, null=True)),
                ('downloadsTimes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manager.profile')),
                ('type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.doctype')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentPattern_Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_object', to='database_manager.object')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_document', to='document.documentspattern')),
            ],
        ),
        migrations.CreateModel(
            name='Document_ParentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentDocumentChanged', models.BooleanField(blank=True, default=False, null=True)),
                ('userRequested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manager.profile')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='document.documentspattern')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_document', to='document.documentspattern')),
            ],
        ),
        migrations.CreateModel(
            name='CreatedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название документа')),
                ('file', models.FileField(blank=True, null=True, upload_to=document.models.user_directory_path)),
                ('json', models.JSONField(blank=True, default=dict, null=True, verbose_name='JSON строка')),
                ('lastUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True, null=True)),
                ('downloadsTimes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentspattern')),
                ('groupofdocument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.groupofdocument')),
            ],
        ),
        migrations.CreateModel(
            name='SavedElements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='JSON строка')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manager.profile')),
                ('type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.doctype')),
            ],
            options={
                'verbose_name': 'Сохраненный элемент',
                'verbose_name_plural': 'Сохраненные элементы',
            },
        ),
        migrations.CreateModel(
            name='Document_VariableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentspattern')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.variableblock')),
            ],
        ),
    ]
