# Generated by Django 5.2.5 on 2025-08-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.FileField(upload_to='dataframes/')),
            ],
        ),
        migrations.CreateModel(
            name='Object_ParentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='database_manager.object')),
                ('parent_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_object', to='database_manager.object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectLink_identificators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_identificator', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_object_identificator', models.CharField(blank=True, max_length=255, null=True)),
                ('object_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_link', to='database_manager.object_parentobject')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('identificator', models.BooleanField(default=False)),
                ('array_separator', models.CharField(blank=True, default=' ', max_length=10, null=True)),
                ('date_format', models.CharField(blank=True, max_length=255, null=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.object')),
            ],
        ),
    ]
