# Generated by Django 4.1.3 on 2023-03-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('owner', models.CharField(max_length=100, verbose_name='Владелец')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='documents/')),
                ('json', models.JSONField(default=dict, verbose_name='JSON строка')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.doctype')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Шрифт',
                'verbose_name_plural': 'Шрифты',
            },
        ),
        migrations.CreateModel(
            name='VariableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('meaning', models.TextField(verbose_name='Значение')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.documents')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
            },
        ),
        migrations.CreateModel(
            name='SavedElements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('json', models.JSONField(verbose_name='JSON строка')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.doctype')),
            ],
            options={
                'verbose_name': 'Сохраненный элемент',
                'verbose_name_plural': 'Сохраненные элементы',
            },
        ),
    ]
