# Generated by Django 4.1.2 on 2022-10-25 15:18

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=False, upload_to=main.models.user_directory_path),
            preserve_default=False,
        ),
    ]
