# Generated by Django 4.1.3 on 2023-05-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='type',
        ),
        migrations.DeleteModel(
            name='Fonts',
        ),
        migrations.RemoveField(
            model_name='savedelements',
            name='type',
        ),
        migrations.RemoveField(
            model_name='variableblock',
            name='doc',
        ),
        migrations.DeleteModel(
            name='DocType',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='SavedElements',
        ),
        migrations.DeleteModel(
            name='VariableBlock',
        ),
    ]
