# Generated by Django 4.1.3 on 2022-11-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_document_options_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('owner', models.CharField(max_length=100, verbose_name='Владелец')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
