# Generated by Django 4.1.3 on 2023-03-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fonts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('json', models.JSONField(verbose_name='JSON строка')),
            ],
            options={
                'verbose_name': 'Шрифт',
                'verbose_name_plural': 'Шрифты',
            },
        ),
    ]
