# Generated by Django 4.1.3 on 2023-03-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_savedelements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedelements',
            options={'verbose_name': 'Сохраненный элемент', 'verbose_name_plural': 'Сохраненные элементы'},
        ),
        migrations.AlterField(
            model_name='savedelements',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
