# Generated by Django 4.1.3 on 2023-03-09 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_doctype_documents_type_savedelements_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctype'),
        ),
        migrations.AlterField(
            model_name='savedelements',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctype'),
        ),
    ]
