# Generated by Django 4.1.3 on 2023-03-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_documents_type_alter_savedelements_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedelements',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
