# Generated by Django 4.1.3 on 2023-03-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_savedelements_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedElements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('json', models.JSONField(verbose_name='JSON строка')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctype')),
            ],
            options={
                'verbose_name': 'Сохраненный элемент',
                'verbose_name_plural': 'Сохраненные элементы',
            },
        ),
    ]
