# Generated by Django 4.1.3 on 2023-03-09 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_savedelements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.doctype'),
        ),
        migrations.AlterField(
            model_name='savedelements',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.doctype'),
        ),
    ]
