# Generated by Django 4.1.3 on 2023-03-09 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_documents_type_alter_savedelements_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('meaning', models.TextField(verbose_name='Значение')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.documents')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
            },
        ),
    ]
