# Generated by Django 4.1.3 on 2023-03-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_variableblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='json',
            field=models.JSONField(default='{}', verbose_name='JSON строка'),
        ),
    ]
