# Generated by Django 4.1.3 on 2023-03-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_documents_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='json',
            field=models.JSONField(default="{'elements': [{'id':'p_0', 'class':'paragraph', 'childs':[], 'style':{'0':'text-align', 'textAlign': 'left'}}]}", verbose_name='JSON строка'),
        ),
    ]
