# Generated by Django 4.1.3 on 2023-03-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_documents_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='json',
            field=models.JSONField(default={'elements': [{'childs': [], 'class': 'paragraph', 'id': 'p_0', 'style': {'0': 'text-align', 'textAlign': 'left'}}]}, verbose_name='JSON строка'),
        ),
    ]
