# Generated by Django 4.1.3 on 2023-03-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_documents_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='json',
            field=models.JSONField(default=dict, verbose_name='JSON строка'),
        ),
    ]
