# Generated by Django 4.1.3 on 2023-03-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_documents_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableblock',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
