# Generated by Django 4.1.3 on 2023-03-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_variableblock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedelements',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
