# Generated by Django 4.1.3 on 2023-05-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='documentOfOrganisation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
