# Generated by Django 5.2.5 on 2025-10-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctype',
            options={'permissions': (('toggle_document_organisation', 'Can change organisation visibility of document'),), 'verbose_name': 'Тип документа', 'verbose_name_plural': 'Типы документов'},
        ),
    ]
