# Generated by Django 4.1.3 on 2023-05-17 03:57

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_documents_documentoforganisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=document.models.user_directory_path),
        ),
    ]
