# Generated by Django 4.1.3 on 2023-05-18 00:55

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_documents_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='dateCreate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=document.models.user_directory_path),
        ),
    ]
