# Generated by Django 4.1.3 on 2023-05-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_documents_datecreate_documents_lastupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
