# Generated by Django 4.1.3 on 2023-06-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_doctype_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_ParentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentDocumentChanged', models.BooleanField(blank=True, default=False, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='document.documents')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_document', to='document.documents')),
            ],
        ),
    ]
