# Generated by Django 4.1.3 on 2023-05-17 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialect', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диалект SQL')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пароль пользователя')),
                ('host', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес базы данных')),
                ('port', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порт для подключения')),
                ('service', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название сервиса')),
            ],
            options={
                'verbose_name': 'Подключение',
                'verbose_name_plural': 'Подключения',
            },
        ),
        migrations.CreateModel(
            name='VariableSQLGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('sql', models.CharField(blank=True, max_length=5000, null=True, verbose_name='SQL-запрос')),
            ],
            options={
                'verbose_name': 'Получаемая sql-переменная',
                'verbose_name_plural': 'Получаемые sql-переменные',
            },
        ),
        migrations.CreateModel(
            name='VariableSQLSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('sql', models.CharField(blank=True, max_length=100, null=True, verbose_name='SQL-название столбца')),
            ],
            options={
                'verbose_name': 'Поисковая sql-переменная',
                'verbose_name_plural': 'Поисковые sql-переменные',
            },
        ),
        migrations.CreateModel(
            name='VariableSQLSet_VariableSQLGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variableGet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manager.variablesqlget')),
                ('variableSet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manager.variablesqlset')),
            ],
        ),
        migrations.CreateModel(
            name='VariableSQLSet_Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.variableblock')),
                ('variableSet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manager.variablesqlset')),
            ],
        ),
        migrations.CreateModel(
            name='VariableSQLGet_Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.variableblock')),
                ('variableGet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manager.variablesqlget')),
            ],
        ),
    ]
