# Generated by Django 5.2.5 on 2025-09-20 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object_parentobject',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='database_manager.object'),
        ),
        migrations.AlterField(
            model_name='object_parentobject',
            name='parent_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='database_manager.object'),
        ),
        migrations.AlterField(
            model_name='objectlink_identificators',
            name='object_identificator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='objectlink_identificators',
            name='object_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row_links', to='database_manager.object_parentobject'),
        ),
        migrations.AlterField(
            model_name='objectlink_identificators',
            name='parent_object_identificator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manager.object'),
        ),
        migrations.AlterUniqueTogether(
            name='object_parentobject',
            unique_together={('object', 'parent_object')},
        ),
        migrations.AlterUniqueTogether(
            name='objectlink_identificators',
            unique_together={('object_link', 'object_identificator', 'parent_object_identificator')},
        ),
    ]
