# Generated by Django 4.1.3 on 2023-05-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariableSQLGet_Variable',
        ),
        migrations.DeleteModel(
            name='VariableSQLSet_Variable',
        ),
    ]
