# Generated by Django 4.1.3 on 2023-05-29 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0002_remove_variablesqlset_variable_variable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='tables',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Таблицы в JSON'),
        ),
        migrations.AddField(
            model_name='variablesqlget',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manager.connection'),
        ),
        migrations.AddField(
            model_name='variablesqlset',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manager.connection'),
        ),
    ]
