# Generated by Django 5.2.5 on 2025-09-20 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0002_alter_object_parentobject_object_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['category__order', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='parameter',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='object_parentobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='database_manager.object'),
        ),
        migrations.AlterField(
            model_name='object_parentobject',
            name='parent_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='database_manager.object'),
        ),
        migrations.AlterField(
            model_name='objectlink_identificators',
            name='object_identificator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='objectlink_identificators',
            name='object_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_links', to='database_manager.object_parentobject'),
        ),
        migrations.AlterField(
            model_name='objectlink_identificators',
            name='parent_object_identificator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.object'),
        ),
        migrations.CreateModel(
            name='ParameterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.object')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('object', 'name')},
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_manager.parametercategory'),
        ),
    ]
