# Generated by Django 5.2.5 on 2025-09-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0003_alter_parameter_options_parameter_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_parentobject',
            name='link_type',
            field=models.CharField(choices=[('single', 'Один элемент'), ('multiple', 'Несколько элементов')], default='single', max_length=10),
        ),
    ]
