# Generated by Django 4.1.3 on 2023-05-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0003_connection_tables_variablesqlget_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
