# Generated by Django 5.2.5 on 2025-09-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0004_object_parentobject_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='linked_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_parameters', to='database_manager.object'),
        ),
    ]
