# Generated by Django 4.1.3 on 2023-05-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0004_connection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='driver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Драйвер'),
        ),
    ]
