# Generated by Django 5.2.5 on 2025-10-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0005_parameter_linked_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['name'], 'permissions': (('manage_object_structure', 'Can manage object structure'), ('manage_object_data', 'Can manage object data'), ('manage_object_links', 'Can manage object links'))},
        ),
    ]
