# Generated by Django 4.1.3 on 2023-05-30 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0005_connection_driver'),
    ]

    operations = [
        
    ]
