# Generated by Django 4.1.3 on 2023-06-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0006_dialect_remove_connection_driver_and_more'),
    ]

    operations = [
       
    ]
