# Generated by Django 4.1.3 on 2023-10-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_profile_canaddorganisationdocument'),
        ('database_manager', '0008_dialect_remove_connection_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_manager.connection')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manager.organisation')),
            ],
        ),
    ]
