# Generated by Django 5.2.5 on 2026-02-28 21:04

import django.db.models.deletion
from django.db import migrations, models


def _build_unique_value(base_value, used_values, suffix_start=2):
    candidate = base_value
    seq = suffix_start
    while candidate in used_values:
        candidate = f"{base_value}_{seq}"
        seq += 1
    used_values.add(candidate)
    return candidate


def bootstrap_link_meta(apps, schema_editor):
    ObjectLinkMeta = apps.get_model("database_manager", "ObjectLinkMeta")
    ObjectParentObject = apps.get_model("database_manager", "Object_ParentObject")
    ObjectLinkIdentificators = apps.get_model("database_manager", "ObjectLink_identificators")
    RecordLink = apps.get_model("database_manager", "RecordLink")

    used_codes_by_parent = {}
    used_display_by_parent = {}
    relation_to_meta = {}

    for relation in ObjectParentObject.objects.all().order_by("parent_object_id", "id"):
        parent_id = relation.parent_object_id
        child_id = relation.object_id
        used_codes = used_codes_by_parent.setdefault(parent_id, set())
        used_display = used_display_by_parent.setdefault(parent_id, set())

        base_code = f"LINK_{child_id}"
        code = _build_unique_value(base_code, used_codes)

        child_name = ""
        if getattr(relation, "object", None) is not None:
            child_name = str(getattr(relation.object, "name", "") or "").strip()
        display_base = f"Связь с {child_name or child_id}"
        display_name = _build_unique_value(display_base, used_display)

        meta = ObjectLinkMeta.objects.create(
            parent_object_id=parent_id,
            child_object_id=child_id,
            object_link_id=relation.id,
            code=code,
            display_name=display_name,
            link_type=relation.link_type or "single",
            order=0,
        )
        relation_to_meta[relation.id] = meta.id

    for relation_id, meta_id in relation_to_meta.items():
        ObjectLinkIdentificators.objects.filter(
            object_link_id=relation_id,
            object_link_meta_id__isnull=True,
        ).update(object_link_meta_id=meta_id)
        RecordLink.objects.filter(
            object_link_id=relation_id,
            object_link_meta_id__isnull=True,
        ).update(object_link_meta_id=meta_id)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("database_manager", "0010_align_objectrecord_legacy_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectLinkMeta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=80)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "link_type",
                    models.CharField(
                        choices=[("single", "single"), ("multiple", "multiple")],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["parent_object_id", "order", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="recordlink",
            name="uniq_record_link_tuple",
        ),
        migrations.AlterUniqueTogether(
            name="objectlink_identificators",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="objectlinkmeta",
            name="child_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_link_meta",
                to="database_manager.object",
            ),
        ),
        migrations.AddField(
            model_name="objectlinkmeta",
            name="object_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_meta",
                to="database_manager.object_parentobject",
            ),
        ),
        migrations.AddField(
            model_name="objectlinkmeta",
            name="parent_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_link_meta",
                to="database_manager.object",
            ),
        ),
        migrations.AddField(
            model_name="objectlink_identificators",
            name="object_link_meta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="row_links",
                to="database_manager.objectlinkmeta",
            ),
        ),
        migrations.AddField(
            model_name="recordlink",
            name="object_link_meta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="record_links",
                to="database_manager.objectlinkmeta",
            ),
        ),
        migrations.RunPython(bootstrap_link_meta, noop_reverse),
        migrations.AddIndex(
            model_name="objectlink_identificators",
            index=models.Index(fields=["object_link"], name="idx_objlink_ident_link"),
        ),
        migrations.AddIndex(
            model_name="objectlink_identificators",
            index=models.Index(fields=["object_link_meta"], name="idx_objlink_ident_meta"),
        ),
        migrations.AddIndex(
            model_name="objectlink_identificators",
            index=models.Index(fields=["parent_object_identificator"], name="idx_objlink_ident_parent"),
        ),
        migrations.AddIndex(
            model_name="objectlink_identificators",
            index=models.Index(fields=["object_identificator"], name="idx_objlink_ident_child"),
        ),
        migrations.AddIndex(
            model_name="recordlink",
            index=models.Index(fields=["object_link_meta"], name="idx_record_link_meta"),
        ),
        migrations.AddConstraint(
            model_name="objectlink_identificators",
            constraint=models.UniqueConstraint(
                condition=models.Q(("object_link_meta__isnull", True)),
                fields=("object_link", "object_identificator", "parent_object_identificator"),
                name="uniq_objlink_ident_legacy",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectlink_identificators",
            constraint=models.UniqueConstraint(
                condition=models.Q(("object_link_meta__isnull", False)),
                fields=("object_link_meta", "object_identificator", "parent_object_identificator"),
                name="uniq_objlink_ident_meta",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("object_link_meta__isnull", True)),
                fields=("object_link", "parent_record", "child_record"),
                name="uniq_record_link_legacy",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("object_link_meta__isnull", False)),
                fields=("object_link_meta", "parent_record", "child_record"),
                name="uniq_record_link_meta",
            ),
        ),
        migrations.AddIndex(
            model_name="objectlinkmeta",
            index=models.Index(fields=["parent_object", "order", "id"], name="idx_linkmeta_parent_order"),
        ),
        migrations.AddIndex(
            model_name="objectlinkmeta",
            index=models.Index(fields=["object_link"], name="idx_linkmeta_relation"),
        ),
        migrations.AddConstraint(
            model_name="objectlinkmeta",
            constraint=models.UniqueConstraint(fields=("parent_object", "code"), name="uniq_linkmeta_parent_code"),
        ),
        migrations.AddConstraint(
            model_name="objectlinkmeta",
            constraint=models.UniqueConstraint(
                fields=("parent_object", "display_name"),
                name="uniq_linkmeta_parent_display",
            ),
        ),
    ]
