# Generated by Django 5.2.5 on 2026-02-28 22:52

import django.db.models.deletion
from django.db import migrations, models


def _normalise(value):
    return str(value or "").strip().lower()


def _desired_name(display_name):
    return f"Связь: {str(display_name or '').strip() or 'Связь'}"


def _desired_type(link_type):
    return "ARRAY" if str(link_type or "single").strip().lower() == "multiple" else "TXTS"


def bind_legacy_link_parameters(apps, schema_editor):
    Parameter = apps.get_model("database_manager", "Parameter")
    ObjectLinkMeta = apps.get_model("database_manager", "ObjectLinkMeta")

    for meta in ObjectLinkMeta.objects.select_related("child_object").order_by("parent_object_id", "order", "id"):
        queryset = Parameter.objects.filter(
            object_id=meta.parent_object_id,
            link_meta_id__isnull=True,
        )
        candidate = None
        by_linked_object = list(queryset.filter(linked_object_id=meta.child_object_id).order_by("id"))
        if len(by_linked_object) == 1:
            candidate = by_linked_object[0]
        else:
            child_name_norm = _normalise(getattr(meta.child_object, "name", ""))
            display_norm = _normalise(meta.display_name)
            desired_norm = _normalise(_desired_name(meta.display_name))
            heuristic = []
            for parameter in queryset.order_by("id"):
                name_norm = _normalise(parameter.name)
                if not name_norm:
                    continue
                if name_norm in {display_norm, desired_norm}:
                    heuristic.append(parameter)
                    continue
                if child_name_norm and child_name_norm in name_norm and ("связь с " in name_norm or "связ" in name_norm):
                    heuristic.append(parameter)
            if len(heuristic) == 1:
                candidate = heuristic[0]
        if candidate is None:
            continue
        candidate.link_meta_id = meta.id
        candidate.is_managed_link_param = True
        candidate.linked_object_id = meta.child_object_id
        candidate.data_type = _desired_type(meta.link_type)
        candidate.name = _desired_name(meta.display_name)
        candidate.save(
            update_fields=[
                "link_meta",
                "is_managed_link_param",
                "linked_object",
                "data_type",
                "name",
            ]
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0011_objectlinkmeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='is_managed_link_param',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parameter',
            name='link_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_parameters', to='database_manager.objectlinkmeta'),
        ),
        migrations.RunPython(bind_legacy_link_parameters, noop_reverse),
    ]
